.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. silk_qt test_silk_qt
clean: FORCE
	$(MAKE) -C .. silk_qt_clean test_silk_qt_clean
check: FORCE
	$(MAKE) -C .. test_silk_qt_check
silk-qt silk-qt.exe: FORCE
	 $(MAKE) -C .. silk_qt
