// Copyright (c) 2009-2016 Satoshi Nakamoto
// Copyright (c) 2009-2016 The Bitcoin Developers
// Copyright (c) 2015-2016 Silk Network Developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#ifndef SILK_CHAINPARAMSSEEDS_H
#define SILK_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the silk network
 * AUTOGENERATED by share/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {

};

static SeedSpec6 pnSeed6_test[] = {

};
#endif // SILK_CHAINPARAMSSEEDS_H
