// Copyright (c) 2009-2019 Satoshi Nakamoto
// Copyright (c) 2009-2019 The Bitcoin Developers
// Copyright (c) 2016-2019 Duality Blockchain Solutions Developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#ifndef SEQUENCE_CHAINPARAMSSEEDS_H
#define SEQUENCE_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the Sequence network
 * AUTOGENERATED by share/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {

};

static SeedSpec6 pnSeed6_test[] = {

};
#endif // SEQUENCE_CHAINPARAMSSEEDS_H
