// Copyright (c) 2009-2017 Satoshi Nakamoto
// Copyright (c) 2009-2017 The Bitcoin Developers
// Copyright (c) 2013-2017 Emercoin Developers
// Copyright (c) 2016-2017 Duality Blockchain Solutions Developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include "stake.h"

#include "chainparams.h"
#include "consensus/consensus.h"
#include "wallet/db.h"
#include "init.h"
#include "timedata.h"
#include "txdb.h"
#include "uint256hm.h"
#include "util.h"
#include "consensus/validation.h"
#include "wallet/wallet.h"


#include <boost/assign/list_of.hpp>

using namespace std;

static const bool fDebugPoS = false;

// Hard checkpoints of stake modifiers to ensure they are deterministic
static std::map<int, unsigned int> mapStakeModifierCheckpoints = {
		{ 0, 0x0e00670bu },
		{ 100, 0x153b2c3au },
		{ 500, 0xe311f3e5u },
		{ 2000, 0xf1bc2587u },
		{ 8000, 0x481e05e4u },
		{ 16000, 0xd6f5eccbu },
		{ 32000, 0x7f331195u },
		{ 64000, 0xa9ee80a2u },
		{ 128000, 0xed217450u },
		{ 196000, 0x29d48eaau },
		{ 256000, 0xcef3ef4fu }
	}
	;

// Get time weight
int64_t GetWeight(int64_t nIntervalBeginning, int64_t nIntervalEnd)
{
	// Kernel hash weight starts from 0 at the min age
	// this change increases active coins participating the hash and helps
	// to secure the network when proof-of-stake difficulty is low

	return nIntervalEnd - nIntervalBeginning - Params().GetConsensus().nStakeMinAge;
}

// Get the last stake modifier and its generation time from a given block
static bool GetLastStakeModifier(const CBlockIndex* pindex, uint64_t& nStakeModifier, int64_t& nModifierTime)
{
	if (!pindex)
		return error("GetLastStakeModifier: null pindex");
	while (pindex && pindex->pprev && !pindex->GeneratedStakeModifier())
		pindex = pindex->pprev;
	if (!pindex->GeneratedStakeModifier())
		return error("GetLastStakeModifier: no generation at genesis block");
	nStakeModifier = pindex->nStakeModifier;
	nModifierTime = pindex->GetBlockTime();
	return true;
}

// Get selection interval section (in seconds)
static int64_t GetStakeModifierSelectionIntervalSection(int nSection)
{
	assert (nSection >= 0 && nSection < 64);
	return (Params().GetConsensus().nModifierInterval * 63 / (63 + ((63 - nSection) * (MODIFIER_INTERVAL_RATIO - 1))));
}

// Get stake modifier selection interval (in seconds)
static int64_t GetStakeModifierSelectionInterval()
{
	int64_t nSelectionInterval = 0;
	for (int nSection=0; nSection<64; nSection++)
		nSelectionInterval += GetStakeModifierSelectionIntervalSection(nSection);
	return nSelectionInterval;
}

// select a block from the candidate blocks in vSortedByTimestamp, excluding
// already selected blocks in vSelectedBlocks, and with timestamp up to
// nSelectionIntervalStop.
static bool SelectBlockFromCandidates(
	vector<pair<int64_t, uint256> >& vSortedByTimestamp,
	map<uint256, const CBlockIndex*>& mapSelectedBlocks,
	int64_t nSelectionIntervalStop, uint64_t nStakeModifierPrev,
	const CBlockIndex** pindexSelected)
{
	bool fSelected = false;
	uint256 hashBest = 0;
	*pindexSelected = (const CBlockIndex*) 0;
	for(const std::pair<int64_t, uint256>& item : vSortedByTimestamp)
	{
		if (!mapBlockIndex.count(item.second))
			return error("SelectBlockFromCandidates: failed to find block index for candidate block %s", item.second.ToString());
		const CBlockIndex* pindex = mapBlockIndex[item.second];
		if (fSelected && pindex->GetBlockTime() > nSelectionIntervalStop)
			break;
		if (mapSelectedBlocks.count(pindex->GetBlockHash()) > 0)
			continue;
		// compute the selection hash by hashing its proof-hash and the
		// previous proof-of-stake modifier
		uint256 hashProof = pindex->IsProofOfStake()? pindex->hashProofOfStake : pindex->GetBlockHash();
		CDataStream ss(SER_GETHASH, 0);
		ss << hashProof << nStakeModifierPrev;
		uint256 hashSelection = Hash(ss.begin(), ss.end());
		// the selection hash is divided by 2**32 so that proof-of-stake block
		// is always favored over proof-of-work block. this is to preserve
		// the energy efficiency property
		if (pindex->IsProofOfStake())
			hashSelection >>= 32;
		if (fSelected && hashSelection < hashBest)
		{
			hashBest = hashSelection;
			*pindexSelected = (const CBlockIndex*) pindex;
		}
		else if (!fSelected)
		{
			fSelected = true;
			hashBest = hashSelection;
			*pindexSelected = (const CBlockIndex*) pindex;
		}
	}
	if (fDebugPoS /*&& GetBoolArg("-printstakemodifier", false)*/)
		LogPrintf("SelectBlockFromCandidates: selection hash=%s\n", hashBest.ToString());
	return fSelected;
}

// Stake Modifier (hash modifier of proof-of-stake):
// The purpose of stake modifier is to prevent a txout (coin) owner from
// computing future proof-of-stake generated by this txout at the time
// of transaction confirmation. To meet kernel protocol, the txout
// must hash with a future stake modifier to generate the proof.
// Stake modifier consists of bits each of which is contributed from a
// selected block of a given block group in the past.
// The selection of a block is based on a hash of the block's proof-hash and
// the previous stake modifier.
// Stake modifier is recomputed at a fixed time interval instead of every 
// block. This is to make it difficult for an attacker to gain control of
// additional bits in the stake modifier, even after generating a chain of
// blocks.
bool ComputeNextStakeModifier(const CBlockIndex* pindexCurrent, uint64_t& nStakeModifier, bool& fGeneratedStakeModifier)
{
	const CBlockIndex* pindexPrev = pindexCurrent->pprev;
	nStakeModifier = 0;
	fGeneratedStakeModifier = false;
	if (!pindexPrev)
	{
		fGeneratedStakeModifier = true;
		return true;  // genesis block's modifier is 0
	}
	// First find current stake modifier and its generation block time
	// if it's not old enough, return the same stake modifier
	int64_t nModifierTime = 0;
	if (!GetLastStakeModifier(pindexPrev, nStakeModifier, nModifierTime))
		return error("ComputeNextStakeModifier: unable to get last modifier");
	if (fDebugPoS)
	{
		LogPrintf("ComputeNextStakeModifier: prev modifier=0x%016" PRIx64 " time=%s epoch=%u\n", nStakeModifier, DateTimeStrFormat(nModifierTime), (unsigned int)nModifierTime);
	}
	if (fDebugPoS)
	{
		int64_t iIfLeft = (nModifierTime / Params().GetConsensus().nModifierInterval);
		int64_t iIfRight = (pindexPrev->GetBlockTime() / Params().GetConsensus().nModifierInterval);
		LogPrintf("ComputeNextStakeModifier: Check PoS Values, nModifierTime=%u, Params().ModifierInterval()=%u, pindexPrev->GetBlockTime()=%u, left=%u, right=%u\n", 
			(int64_t)nModifierTime, (int64_t)Params().GetConsensus().nModifierInterval, (int64_t)pindexPrev->GetBlockTime(), iIfLeft, iIfRight);
	}

	if (nModifierTime / Params().GetConsensus().nModifierInterval >= pindexPrev->GetBlockTime() / Params().GetConsensus().nModifierInterval)
	{
		if (fDebugPoS)
		{
			LogPrintf("ComputeNextStakeModifier: no new interval keep current modifier: pindexPrev nHeight=%d nTime=%u\n", pindexPrev->nHeight, (unsigned int)pindexPrev->GetBlockTime());
		}
		return true;
	}
	if (nModifierTime / Params().GetConsensus().nModifierInterval >= pindexCurrent->GetBlockTime() / Params().GetConsensus().nModifierInterval)
	{
		if (fDebugPoS)
		{
			LogPrintf("ComputeNextStakeModifier: no new interval keep current modifier: pindexCurrent nHeight=%d nTime=%u\n", pindexCurrent->nHeight, (unsigned int)pindexCurrent->GetBlockTime());
		}
		return true;
	}

	// Sort candidate blocks by timestamp
	vector<pair<int64_t, uint256> > vSortedByTimestamp;
	vSortedByTimestamp.reserve(64 * Params().GetConsensus().nModifierInterval / Params().GetConsensus().nPoSTargetSpacing);
	int64_t nSelectionInterval = GetStakeModifierSelectionInterval();
	int64_t nSelectionIntervalStart = (pindexPrev->GetBlockTime() / Params().GetConsensus().nModifierInterval ) * Params().GetConsensus().nModifierInterval - nSelectionInterval;
	const CBlockIndex* pindex = pindexPrev;
	while (pindex && pindex->GetBlockTime() >= nSelectionIntervalStart)
	{
		vSortedByTimestamp.push_back(make_pair(pindex->GetBlockTime(), pindex->GetBlockHash()));
		pindex = pindex->pprev;
	}
	int nHeightFirstCandidate = pindex ? (pindex->nHeight + 1) : 0;
	reverse(vSortedByTimestamp.begin(), vSortedByTimestamp.end());
	sort(vSortedByTimestamp.begin(), vSortedByTimestamp.end());

	// Select 64 blocks from candidate blocks to generate stake modifier
	uint64_t nStakeModifierNew = 0;
	int64_t nSelectionIntervalStop = nSelectionIntervalStart;
	map<uint256, const CBlockIndex*> mapSelectedBlocks;
	for (int nRound=0; nRound<min(64, (int)vSortedByTimestamp.size()); nRound++)
	{
		// add an interval section to the current selection round
		nSelectionIntervalStop += GetStakeModifierSelectionIntervalSection(nRound);
		// select a block from the candidates of current round
		if (!SelectBlockFromCandidates(vSortedByTimestamp, mapSelectedBlocks, nSelectionIntervalStop, nStakeModifier, &pindex))
			return error("ComputeNextStakeModifier: unable to select block at round %d", nRound);
		// write the entropy bit of the selected block
		nStakeModifierNew |= (((uint64_t)pindex->GetStakeEntropyBit()) << nRound);
		// add the selected block from candidates to selected list
		mapSelectedBlocks.insert(make_pair(pindex->GetBlockHash(), pindex));
		if (fDebugPoS && GetBoolArg("-printstakemodifier", false))
			LogPrintf("ComputeNextStakeModifier: selected round %d stop=%s height=%d bit=%d\n",
				nRound, DateTimeStrFormat(nSelectionIntervalStop), pindex->nHeight, pindex->GetStakeEntropyBit());
	}

	// Print selection map for visualization of the selected blocks
	//if (fDebugPoS && GetBoolArg("-printstakemodifier", false))
	//{
		string strSelectionMap = "";
		// '-' indicates proof-of-work blocks not selected
		strSelectionMap.insert(0, pindexPrev->nHeight - nHeightFirstCandidate + 1, '-');
		pindex = pindexPrev;
		while (pindex && pindex->nHeight >= nHeightFirstCandidate)
		{
			// '=' indicates proof-of-stake blocks not selected
			if (pindex->IsProofOfStake())
				strSelectionMap.replace(pindex->nHeight - nHeightFirstCandidate, 1, "=");
			pindex = pindex->pprev;
		}
		for(const std::pair<uint256, const CBlockIndex*>& item : mapSelectedBlocks)
		{
			// 'S' indicates selected proof-of-stake blocks
			// 'W' indicates selected proof-of-work blocks
			strSelectionMap.replace(item.second->nHeight - nHeightFirstCandidate, 1, item.second->IsProofOfStake()? "S" : "W");
		}
		LogPrintf("ComputeNextStakeModifier: selection height [%d, %d] map %s\n", nHeightFirstCandidate, pindexPrev->nHeight, strSelectionMap);
	//}
	if (fDebugPoS)
	{
		LogPrintf("ComputeNextStakeModifier: new modifier=0x%016" PRIx64 " time=%s\n", nStakeModifierNew, DateTimeStrFormat(pindexPrev->GetBlockTime()));
	}

	nStakeModifier = nStakeModifierNew;
	fGeneratedStakeModifier = true;
	return true;
}

struct StakeMod
{
	uint64_t nStakeModifier;
	int64_t nStakeModifierTime;
	int nStakeModifierHeight;
};

// The stake modifier used to hash for a stake kernel is chosen as the stake
// modifier about a selection interval later than the coin generating the kernel
static bool GetKernelStakeModifier(uint256 hashBlockFrom, uint64_t& nStakeModifier, int& nStakeModifierHeight, int64_t& nStakeModifierTime, bool fPrintProofOfStake)
{
#ifdef ENABLE_WALLET
	// init internal cache for stake modifiers (this is used only to reduce CPU usage)
	static uint256HashMap<StakeMod> StakeModCache;
	static bool initCache = false;
	if (initCache == false)
	{
		std::vector<COutput> vCoins;
		pwalletMain->AvailableCoins(vCoins, false);
		StakeModCache.Set(vCoins.size() + 1000);
		initCache = true;
	}

	// Clear cache after every new block.
	// If cache is not cleared here it will result in blockchain unable to be downloaded.
	static int nClrHeight = 0;
	bool fSameBlock;

	if (nClrHeight < chainActive.Height())
	{
		nClrHeight = chainActive.Height();
		StakeModCache.clear();
		fSameBlock = false;
	}
	else
	{
		uint256HashMap<StakeMod>::Data *pcache = StakeModCache.Search(hashBlockFrom);
		if (pcache != NULL)
		{
			nStakeModifier = pcache->value.nStakeModifier;
			nStakeModifierHeight = pcache->value.nStakeModifierHeight;
			nStakeModifierTime = pcache->value.nStakeModifierTime;
			return true;
		}
		fSameBlock = true;
	}
#endif

	nStakeModifier = 0;
	if (!mapBlockIndex.count(hashBlockFrom))
		return error("GetKernelStakeModifier() : block not indexed");
	const CBlockIndex* pindexFrom = mapBlockIndex[hashBlockFrom];
	nStakeModifierHeight = pindexFrom->nHeight;
	nStakeModifierTime = pindexFrom->GetBlockTime();
	int64_t nStakeModifierSelectionInterval = GetStakeModifierSelectionInterval();

	if(fDebugPoS)
		LogPrintf("GetKernelStakeModifier(): nStakeModifierSelectionInterval = %d,nStakeModifierTime=%d, nStakeModifierSelectionInterval=%d\n", 
			nStakeModifierSelectionInterval, nStakeModifierTime, nStakeModifierSelectionInterval);

	const CBlockIndex* pindex = pindexFrom;
	// loop to find the stake modifier later by a selection interval
	while (nStakeModifierTime < pindexFrom->GetBlockTime() + nStakeModifierSelectionInterval)
	{
		if(fDebugPoS)
			LogPrintf("GetKernelStakeModifier(): nStakeModifierTime = %d,pindexFrom->GetBlockTime()=%d, nStakeModifierSelectionInterval=%d, nDiff=%d.\n", 
				nStakeModifierTime, pindexFrom->GetBlockTime(), nStakeModifierSelectionInterval, nStakeModifierTime - (pindexFrom->GetBlockTime() + nStakeModifierSelectionInterval));

		if (!chainActive.Next(pindex))
		{   // reached best block; may happen if node is behind on block chain

			if(fDebugPoS)
			{
				int64_t nLetfSide = pindex->GetBlockTime() + Params().GetConsensus().nStakeMinAge - nStakeModifierSelectionInterval;
				LogPrintf("GetKernelStakeModifier(): reached best block but no PoS; GetBlockTime=%d, StakeMinAge=%d, nLetfSide=%d, nRightSide=%d, ndiff=%d\n", 
					pindex->GetBlockTime(), Params().GetConsensus().nStakeMinAge, nLetfSide, GetAdjustedTime(), nLetfSide - GetAdjustedTime());
			}

			if (fPrintProofOfStake || (pindex->GetBlockTime() + Params().GetConsensus().nStakeMinAge - nStakeModifierSelectionInterval > GetAdjustedTime()))
				return error("GetKernelStakeModifier() : reached best block %s at height %d from block %s",
					pindex->GetBlockHash().ToString(), pindex->nHeight, hashBlockFrom.ToString());
			else
			{
				return false;
			}
			
		}
		pindex = chainActive.Next(pindex);
		if (pindex->GeneratedStakeModifier())
		{
			nStakeModifierHeight = pindex->nHeight;
			nStakeModifierTime = pindex->GetBlockTime();
			if(fDebugPoS)
				LogPrintf("GetKernelStakeModifier(): GeneratedStakeModifier = true. pindexFrom->GetBlockTime() = %d, nHeight = %d, nStakeModifierHeight = %d, nStakeModifierTime = %d.\n", 
					pindexFrom->GetBlockTime(), pindex->nHeight, nStakeModifierHeight, nStakeModifierTime);
		}
	}
	nStakeModifier = pindex->nStakeModifier;

	if(fDebugPoS)
		LogPrintf("GetKernelStakeModifier(): PoS Stake Modifier Good! nStakeModifierTime = %d.\n", nStakeModifier);

#ifdef ENABLE_WALLET
	// Save to cache only at minting phase
	if (fSameBlock)
	{
		struct StakeMod sm;
		sm.nStakeModifier = nStakeModifier;
		sm.nStakeModifierHeight = nStakeModifierHeight;
		sm.nStakeModifierTime = nStakeModifierTime;
		StakeModCache.Insert(hashBlockFrom, sm);
	}
	return true;
#endif
}

// ppcoin kernel protocol
// coinstake must meet hash target according to the protocol:
// kernel (input 0) must meet the formula
//     hash(nStakeModifier + txPrev.block.nTime + txPrev.offset + txPrev.nTime + txPrev.vout.n + nTime) < bnTarget * nCoinDayWeight
// this ensures that the chance of getting a coinstake is proportional to the
// amount of coin age one owns.
// The reason this hash is chosen is the following:
//   nStakeModifier: 
//       (v0.3) scrambles computation to make it very difficult to precompute
//              future proof-of-stake at the time of the coin's confirmation
//       (v0.2) nBits (deprecated): encodes all past block timestamps
//   txPrev.block.nTime: prevent nodes from guessing a good timestamp to
//                       generate transaction for future advantage
//   txPrev.offset: offset of txPrev inside block, to reduce the chance of 
//                  nodes generating coinstake at the same time
//   txPrev.nTime: reduce the chance of nodes generating coinstake at the same
//                 time
//   txPrev.vout.n: output number of txPrev, to reduce the chance of nodes
//                  generating coinstake at the same time
//   block/tx hash should not be used here as they can be generated in vast
//   quantities so as to generate blocks faster, degrading the system back into
//   a proof-of-work situation.
//
bool CheckStakeKernelHash(unsigned int nBits, const CBlock& blockFrom, unsigned int nTxPrevOffset, const CTransaction& txPrev, const COutPoint& prevout, unsigned int nTimeTx, uint256& hashProofOfStake, bool fPrintProofOfStake)
{
	if(fDebugPoS) 
		LogPrintf("CheckStakeKernelHash() function called.\n");

	if (nTimeTx < txPrev.nTime)  // Transaction timestamp violation
		return error("CheckStakeKernelHash() : nTime violation");

	unsigned int nTimeBlockFrom = blockFrom.GetBlockTime();
	if (nTimeBlockFrom + Params().GetConsensus().nStakeMinAge > nTimeTx) // Min age requirement
		return error("CheckStakeKernelHash() : min age violation");

	uint256 bnTargetPerCoinDay;
	bnTargetPerCoinDay.SetCompact(nBits);
	int64_t nValueIn = txPrev.vout[prevout.n].nValue;
	// v0.3 protocol stake.hash weight starts from 0 at the 30-day min age
	// this change increases active coins participating the hash and helps
	// to secure the network when proof-of-stake difficulty is low
	int64_t nTimeWeight = min((int64_t)nTimeTx - txPrev.nTime, Params().GetConsensus().nStakeMaxAge) - (Params().GetConsensus().nStakeMinAge);
	uint256 bnCoinDayWeight = uint256(nValueIn) * nTimeWeight / COIN / (24 * 60 * 60);
	// Calculate hash
	CDataStream ss(SER_GETHASH, 0);
	uint64_t nStakeModifier = 0;
	int nStakeModifierHeight = 0;
	int64_t nStakeModifierTime = 0;

	if (!GetKernelStakeModifier(blockFrom.GetHash(), nStakeModifier, nStakeModifierHeight, nStakeModifierTime, fPrintProofOfStake))
		return false;
	ss << nStakeModifier;

	ss << nTimeBlockFrom << nTxPrevOffset << txPrev.nTime << prevout.n << nTimeTx;

	hashProofOfStake = Hash(ss.begin(), ss.end());
	if (fPrintProofOfStake)
	{
		LogPrintf("CheckStakeKernelHash() : using modifier 0x%016x at height=%d timestamp=%s for block from height=%d timestamp=%s\n",
			nStakeModifier, nStakeModifierHeight,
			DateTimeStrFormat(nStakeModifierTime),
			mapBlockIndex[blockFrom.GetHash()]->nHeight,
			DateTimeStrFormat(blockFrom.GetBlockTime()));
		LogPrintf("CheckStakeKernelHash() : check modifier=0x%016x nTimeBlockFrom=%u nTxPrevOffset=%u nTimeTxPrev=%u nPrevout=%u nTimeTx=%u hashProof=%s\n",
			nStakeModifier,
			nTimeBlockFrom, nTxPrevOffset, txPrev.nTime, prevout.n, nTimeTx,
			hashProofOfStake.ToString());
	}

	// Now check if proof-of-stake hash meets target protocol
	if (uint256(hashProofOfStake) > bnCoinDayWeight * bnTargetPerCoinDay)
		return false;

	if (fDebug && !fPrintProofOfStake)
	{
		LogPrintf("CheckStakeKernelHash() : using modifier 0x%016" PRIx64 " at height=%d timestamp=%s for block from height=%d timestamp=%s\n",
			nStakeModifier, nStakeModifierHeight,
			DateTimeStrFormat(nStakeModifierTime),
			mapBlockIndex[blockFrom.GetHash()]->nHeight,
			DateTimeStrFormat(blockFrom.GetBlockTime()));

		LogPrintf("CheckStakeKernelHash() : pass protocol=%s modifier=0x%016" PRIx64 " nTimeBlockFrom=%u nTxPrevOffset=%u nTimeTxPrev=%u nPrevout=%u nTimeTx=%u hashProof=%s\n",
			nStakeModifier,
			nTimeBlockFrom, nTxPrevOffset, txPrev.nTime, prevout.n, nTimeTx,
			hashProofOfStake.ToString());
	}
	return true;
}

// Check stake.hash target and coinstake signature
bool CheckProofOfStake(CValidationState& state,const CTransaction& tx, unsigned int nBits, uint256& hashProofOfStake)
{
	if (!tx.IsCoinStake())
		return error("CheckProofOfStake() : called on non-coinstake %s", tx.GetHash().ToString());

	// Kernel (input 0) must match the stake hash target per coin age (nBits)
	const CTxIn& txin = tx.vin[0];

	// Transaction index is required to get to block header
	if (!fTxIndex)
		return error("CheckProofOfStake() : transaction index not available");

	// First try finding the previous transaction in database
	CTransaction txTmp;
	uint256 hashBlock = 0;
	if (!GetTransaction(txin.prevout.hash, txTmp, Params().GetConsensus(), hashBlock))
		return state.DoS(1, error("CheckProofOfStake() : txPrev not found")); // previous transaction not in main chain, may occur during initial download

	// Verify signature
	CCoins coins(txTmp, 0);
	if (!CScriptCheck(coins, tx, 0, true, 0)())
		return state.DoS(100, error("CheckProofOfStake() : VerifySignature failed on coinstake %s", tx.GetHash().ToString()));

	// Get transaction index for the previous transaction
	CDiskTxPos postx;
	if (!pblocktree->ReadTxIndex(txin.prevout.hash, postx))
		return error("CheckProofOfStake() : tx index not found");  // tx index not found

	// Read txPrev and header of its block
	CBlockHeader header;
	CTransaction txPrev;
	{
		CAutoFile file(OpenBlockFile(postx, true), SER_DISK, CLIENT_VERSION);
		try {
			file >> header;
			fseek(file.Get(), postx.nTxOffset, SEEK_CUR);
			file >> txPrev;
		} catch (const std::exception& e) {
			return error("%s() : deserialize or I/O error in CheckProofOfStake()", __PRETTY_FUNCTION__);
		}
		if (txPrev.GetHash() != txin.prevout.hash)
			return error("%s() : txid mismatch in CheckProofOfStake()", __PRETTY_FUNCTION__);
	}

	//if (!CheckStakeKernelHash(nBits, block, txindex.pos.nTxPos - txindex.pos.nBlockPos, txPrev, txin.prevout, tx.nTime, hashProofOfStake, fDebug))
	if (!CheckStakeKernelHash(nBits, header, postx.nTxOffset + CBlockHeader::NORMAL_SERIALIZE_SIZE, txPrev, txin.prevout, tx.nTime, hashProofOfStake, true))
		return state.DoS(1, error("CheckProofOfStake() : INFO: check kernel failed on coinstake %s, hashProof=%s", tx.GetHash().ToString(), hashProofOfStake.ToString())); // may occur during initial download or if behind on block chain sync

	return true;
}

// Check whether the coinstake timestamp meets protocol
bool CheckCoinStakeTimestamp(int64_t nTimeBlock, int64_t nTimeTx)
{
	return (nTimeBlock == nTimeTx);
}

// Get stake modifier checksum
unsigned int GetStakeModifierChecksum(const CBlockIndex* pindex)
{
	assert (pindex->pprev || pindex->GetBlockHash() == Params().GetConsensus().hashGenesisBlock);
	// Hash previous checksum with flags, hashProofOfStake and nStakeModifier
	CDataStream ss(SER_GETHASH, 0);
	if (pindex->pprev)
		ss << pindex->pprev->nStakeModifierChecksum;
	ss << pindex->nFlags << pindex->hashProofOfStake << pindex->nStakeModifier;
	uint256 hashChecksum = Hash(ss.begin(), ss.end());
	hashChecksum >>= (256 - 32);
	return hashChecksum.GetLow64();
}

// Check stake modifier hard checkpoints
bool CheckStakeModifierCheckpoints(int nHeight, unsigned int nStakeModifierChecksum)
{   
	if (Params().NetworkIDString() != "main") return true; // Testnet or Regtest has no checkpoints
	if (mapStakeModifierCheckpoints.count(nHeight))
		return nStakeModifierChecksum == mapStakeModifierCheckpoints[nHeight];
	return true;
}
