#!/bin/bash

# This is a thin wrapper around sequence-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using sequence-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_sequenced

# Grab the value of $REAL_SEQUENCECLI which may be sequence-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_SEQUENCECLI}" "$@" | sed 's/\r//'
