#!/bin/bash

# This is a thin wrapper around silk-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using silk-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_silkd

# Grab the value of $REAL_SILKCLI which may be silk-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_SILKCLI}" "$@" | sed 's/\r//'
